### ISSUE TITLE
Error waiting for the master to be up. DNS pods stay pending.

### ISSUE THREAD

**Issue by carlosedp** [ReSearchITEng/kubeadm-playbook#4]
This task fails because the "dns" pod is not scheduled since no taint for master is made (error in issue #2 ) and no nodes are up yet.

```
- name: sanity - wait for alls pod to be running (important to ensure network is fine, see cni bugs)
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: "kubectl get --namespace kube-system pods | tail -n +2 | grep -v -w 'Running' |grep -v 'dns' || true "
  register: command_result
  tags:
  - k8s_network_addons
  - sanity
  until: command_result.stdout == ""
  retries: 40
  delay: 3
```
