### ISSUE TITLE
admin conf not getting generated correclty 

### ISSUE THREAD

**Issue by gallexme** [ReSearchITEng/kubeadm-playbook#81]
I Used a FQDN in in the Inventory File
Thats the Result:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1URXdOakU0TlRJMU5Wb1hEVEk1TVRFd016RTROVEkxTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTnpQCkJJbnZiSjkxRmVRTHpWQWFpTnVHNmxkVTUraU5NQTV1Z0JlZDNibWVNakZoaVUvdFRzUXozQ2xkZGxIQjBiSHoKYUJJdGo2N2Q0TDNuaXlOQUJOMGMvTnRqZ05QR2Z1UktHMWlsaE1nSHN4UjJSaEFoSFJub1N1cFRJUTdSL1NwUQpvS3NKTWxMTWZwS1hUTmo2VVhOQ2JHR2F1bERKZG5VTXhjZm4yMU4rYy9MeEFtcWhadkhSb21ybjE2SjBFWU1hCkVQNVZ3aldhWlRxaTMyR2lGVG11SlNrVEtNWGEyT01RV1dYYmh4eXVGRFlQdXVtWFIyKzhxQlZFSFFzQ1dSQ1oKWXlQQVhIMlhXUVNjN1RjcFFoS1oxbldXbWF3V0d6emVmc3liamVoTk5IL2toUGpjd3VPU29oR1QrYzVTNUNVUQp6RnFwL2poVE5xQVdhaFVPaGxVQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCQmZzVDhFMllXZENjMGVTS1luOGRyOWdDNloKdmxoVjMxUDNISno0MXhCNEp4QXBpWllFZXFKMTQ5S3dCSWFyMGU5Y2NSeUdKM21Benp6TnhVS3ozSGliQlBRYgpzYXd1NXpKRUpLSHJYSVdRMStlN1FEMU83TXhZNVVzbGMvbjNnVlBQQ3gyTUQ0TjJQeUJRRERydFdRaEVCcWFkCmcyL015V1BVdnpodkZqSXBVYjJZdHRvYisvVFJVb3U2Uk0zK2VsU1dnVGNyR2FkS2s3dkZkb1k1YUNuUlhNNE8KSXZIa0xIQ0Z2c1VFNk9zcldFTzY5TFpPdXFiSVd5SjJiVWxKV0tKNWp5Y3VHZ05kZGtuT1hQUTJkTFFoMGJaTAp5aVVHbkpsL2lyR3RlYVl2K0l5K0p4dU9RZkFmZE5xZkcyVFhjaWs5OUNhR0lBWXBiWjByRFJjU0Z1UT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    ²-210-136-24.rev.poneytelecom.eu:6443
  name: node0
contexts:
- context:
    cluster: node0
    user: kubernetes-admin
  name: kubernetes-admin@node0
current-context: kubernetes-admin@node0
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJWUFnWFhUbktodlF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB4T1RFeE1EWXhPRFV5TlRWYUZ3MHlNREV4TURVeE9EVXlOVGhhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTAxU21CMmZnRVg0bnFYWEwKYnlEU1ZsWEtoZmg4WVBuN1h3MElrcjgwbHpRekhBQmczSUo4N1A0MFBZTUNVNHZxRE50Vm96TFVvMmxndUt1KwpFNnIySFp5bmQ4VFVHWVlFb2w3QjYrMEdtM2grRnRFZDRDTHo4R3BBQ2tmYmY4VENEczF5SERRa21BekdPNkI5CnJ5ZE11ZGdGVFd6U2VONUJxSmgwbGlkdG1SWEoxRUF1eEFMTFltc1FUZVV1MzBobVJabEdkbkpFenE1d3l4ZUoKQTE1bGZGdkpFUm5mWjZ1RExEaEhoVUZ2MWEvaExKOE9OV1pGeFdwSTUzRVlONGtNaHlCb0VxS3RDMG1FTmNOcApMdU9TL1pzQXU1aWlUOGRLSEJZRVZYcy9maUJ2ems5b3pTbG9TMmRhK1dyKzBaMUlmSXliY2dOY1pNSnArcm91CnhtVzFWUUlEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJa2NKMFZDaE8wYnEveXRlTVZuK01JZUtoS25seFR6aEh2cApQc2dYRVlRdHZUcTk0ZFJ4M1F6L1hFYlNHRTVHVWQwcGJFOVRSSGREcXVGV0VYQkFYNUwrR25oS0hQNE4yU2pTCnBWUkpwSE9uU045QzVoMEFRbGFXZFI3MW82T20yY21pUXdtMUxkRWY3c0RiMWV4MWpoTWo1UFlUWWZsd21XVGMKM2Nza0NTWVl5T0VBNU93Q0tNZGhkMHRQbHZPMlQ2a3hmdldmeU1TUkdSMVlQdVRBU0xKQkpVRm42VUZGRWo4bAo4MkdDbWs1ZEIrMUZaQXA2RmczUFlmL25WOXhHNThYU1VjM0kvVmFBaVRaaStTUWVLb3luclJyeTl3eUFDSEtzCjhEbmNuZWhNV2gyZldGYmJZUFluUk0rZE9TSFFqQnRuTU5UVmJ2WkNBWDFCVktUMUNlMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMDFTbUIyZmdFWDRucVhYTGJ5RFNWbFhLaGZoOFlQbjdYdzBJa3I4MGx6UXpIQUJnCjNJSjg3UDQwUFlNQ1U0dnFETnRWb3pMVW8ybGd1S3UrRTZyMkhaeW5kOFRVR1lZRW9sN0I2KzBHbTNoK0Z0RWQKNENMejhHcEFDa2ZiZjhUQ0RzMXlIRFFrbUF6R082QjlyeWRNdWRnRlRXelNlTjVCcUpoMGxpZHRtUlhKMUVBdQp4QUxMWW1zUVRlVXUzMGhtUlpsR2RuSkV6cTV3eXhlSkExNWxmRnZKRVJuZlo2dURMRGhIaFVGdjFhL2hMSjhPCk5XWkZ4V3BJNTNFWU40a01oeUJvRXFLdEMwbUVOY05wTHVPUy9ac0F1NWlpVDhkS0hCWUVWWHMvZmlCdnprOW8KelNsb1MyZGErV3IrMFoxSWZJeWJjZ05jWk1KcCtyb3V4bVcxVlFJREFRQUJBb0lCQUdNWk1ySU9WOWhjSENVdgpBN0tjNVlWdXZZV05QR1lOVTM4REVaNGU0MzUwRC9OMWlmWmRpazluOVA5VFMrZjVtRXRuSHdWa2RLb2NaQ3EwCi9uRWluajdNa3d0cTFUc1N5V0dLcGMwSVhTelNsKzRES2N0TkdLOElZL2R1TXRQN1pEU2t5bm5IU2RHelM5SHkKTkgzS0pBU1I5QXFXbVN2c3JVVnVHRjNCSjNlOUVNcXhuSmNneE9hczQvbGZUOFZLMXgyMk51VitNM09yZWdrUwoyc0d5TkFVcGF2TzVCOUQ2WDJuT3Q3amNISjdoNEYwU0lxMFBJRUxucGlKdDJYSGVUU3pKSXRiQTlpT1JSWGxwCmF0OTJ3VWJXK3FFcXFHYzlab1J6bzJyOE1SSWRrc0praG9RZXFqOUljR1JuY0RPYWxTU1NVeXB6amFwWHRjS2sKcVp3QWp4RUNnWUVBLzJiZGVWSFlNZG05WnJnVVJabURqT09BVmNMSkl3Mld5bzZiR2gwa0tLMGJNdEVWWE04dApkWjM4U2JxUGVSZHloNG1yaXhTZUJWMDVDc2xqbDQzeFhqVUZkdGpSN21pbFBUQkFxS081TXdic2FsR0htc3l0CkFlSDdoMElMRVhNcTR0UDVPYk9hWnBsVGlKRHVER1ZpYTJqVFpFQVhRb0loMzAwNE80V0UwczhDZ1lFQTA5TmIKNnRvdVhWeXVQWG1xbFZWb1ljSTNLQjJ0UVhXcUF1VSsvZkJaVDZRT280a09UMllnalltVnh1SW5jRjdqc1FMYwpEb3dHZTZJMEtvcUNzUElxa0p0S2JVYyt3c3ZEam5pa1JSNHBST1RyalM3eUQ4c0d0VjV3SDNVUjZvekpVOHp0ClVUOXZHVy9RYzNBdnZSNUZRTmhaNDJ2WCtZUHozLzNTbmRrUlRwc0NnWUJxTE94VG5EZkJlYUNvakV3NUp2bXUKWDRHaHBZbVNuZnFiR0svWUtsYzI1Y2dSMXlRSFlrV215TmZ5R3JHOGlJZmZXdGRLeVhac0NuWkZTcld4Y3B2dQpLeUtyWnJYWFkvK1ZzWEtmNlBoOEF4dlRrek5Kb2w4bUVqbEw0S1BUVEVwKzQ5cVBKMkEvMk93R01TSVZXeXlRCk5KTDA4VVA2TFRsQnFNdUF5eUFOdHdLQmdRRE1VN2Y1ZmNaMWxuNFluTERZWmM5UFpWbHhIOWROS21QNWNRcm4KUngzUGZkQUZIYUtwSWpsS2Jpb0U4NGZabEI2TVU5YlRUV3kvZTRKWWVzMkFROGlkUHI1M1ZOOE1aaU5YM2JXUApXbjJ5a0NOTFI3cUZVM0ZBS0QxOWlwN2lvalZkMlhJZUNsTnZ0UFRkTloxSER0ajhxUFZrTTFYY3dOVFEvdlZYCi85ZjYrd0tCZ1FEZ25GaGNVMXVwSjhodVZ1UHptY2t0WWh6VFVhRjhKWndFQnZlaVNhclpVWkw3bWFwdURHWEYKVmV6S2Flc3ZjVCsyeithd2ppTjdoUnBLTEwwWk51OHFTTXpFM3dTK3R0SlZLRm9PT0tqdnY3VVFxaWc2NG5xVQoyNWQyWXd1UU4xMFNBdURhS0dhcDZzRkdoZ01DaFR3OEZoTTUrbzlhUlhQMW42Y292RzNrVkE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
```

```ini

# Use FullyQualifiedDomainNames (FQDN) (e.g. machine1.corp.example.com)
[all:vars]
ansible_connection=ssh
ansible_user=root
[primary-master]
master.h0st.space

[secondary-masters]
# If there is only one master, make this section empty

[masters:children]
primary-master
secondary-masters

[nodes]
# If there is only one machine both master and node, make this section empty
# Best practice is to have few machines allocated for Prometheus/Ingresses/eventual ELK. 
#      These are usually labeled "infra", and tainted with NoSchedule or at least PreferNoSchedule
#      See "taint_for_label" in group_vars/all/global.yaml
#node[1:2].corp.example.com label=node-role.kubernetes.io/infra=
# All other nodes are automatically labeled "compute" and without any taint.

node[0:0].h0st.space label=node-role.kubernetes.io/infra=

[node:children]
nodes
```
