### ISSUE TITLE
any state "Installed" Package Installation doesnt work on Ubuntu 

### ISSUE THREAD

**Issue by gallexme** [ReSearchITEng/kubeadm-playbook#82]
Example:
```yaml
- name: Install kubectl # ansible bug 29705
  package: name="{{ item }}={{kubectl_version | regex_replace('v')}}*" state=installed
  #environment: '{{ proxy_env | default ({}) }}'
  with_items:
  - kubectl
  when: kubectl_version is defined and ( kubectl_version!='installed' or kubectl_version!='latest' ) and ansible_os_family == "Debian"
```
state=installed doesnt exist in apt

(item=kubelet) => {"ansible_loop_var": "item", "changed": false, "item": "kubelet", "msg": "value of state must be one of: absent, build-dep, fixed, latest, present, got: installed"}

either change to latest/fixed/present
